Hw6
emapfff/java-backend-2024 pull request #10
Opened 2024-03-24 15:32 UTC by emapfff

2024-03-29 23:42 UTC, emapfff commented
К 6 домашке требовалось интеграцию клиентов, я ее сделал. Вот несколько скринов полностью рабочего приложения с бэком)
![tg1](https://github.com/emapfff/java-backend-2024/assets/88779154/2769f5b6-61b0-4c9a-9e11-06b79de494af)
![tg2](https://github.com/emapfff/java-backend-2024/assets/88779154/de228dd0-1e44-4eb3-98f7-d09683ffe655)
![tg3](https://github.com/emapfff/java-backend-2024/assets/88779154/717ad0d7-ec58-4e27-9802-e520fc826f56)

2024-04-15 12:17 UTC, iskanred requested changes
Нужны минорные правки, но в целом выглядит уже очень лаконично!

Едиственное - поробуй написать методы jpa интерфейсов без аннотаций кверей, если получится. Чисто на нейминге

https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html
https://www.baeldung.com/spring-data-derived-queries

В целом все круто по заданию и тесты есть, поэтому - 8/8 💯

2024-04-15 12:17 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JpaConfig.java
> +    @Primary
primary не нужно)

2024-04-15 12:17 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JpaConfig.java
> +    public JpaLinkRepository jpaLinkRepository(
лучше возвращаемый тип методов делать интерфейсами, а не реализациями

2024-04-15 12:17 UTC, iskanred commented on scrapper/src/test/java/edu/java/domain/jpa/JpaChatRepositoryTest.java
> +import static org.junit.jupiter.api.Assertions.*;
перенос строки поехал

2024-04-15 12:17 UTC, iskanred commented on scrapper/src/test/java/edu/java/tools/LinkParserTest.java
> +    }
надо бы еще добавить тестов на битые ссылки всякие типа с несолькими слешами или странными символами

2024-04-15 12:17 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/jpa/bases/BaseJpaChatRepository.java
> +    @Query("select c from Chat c where c.tgChatId= :tgChatId")
без кверей не получается, чтоб spring чисто по неймингу смог сам запрос сформировать?

2024-04-15 12:17 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/jpa/bases/BaseJpaGithubLinkRepository.java
> +    @Query("SELECT gl FROM GithubLink gl WHERE gl.link = :link")
попробуй без кверей, соблюдая нейминг spring data для jpa

2024-04-15 14:03 UTC, emapfff commented on scrapper/src/main/java/edu/java/configuration/JpaConfig.java
> +    @Primary
я в 7 пр исправил

2024-04-15 14:03 UTC, emapfff commented on scrapper/src/main/java/edu/java/configuration/JpaConfig.java
> +    public JpaLinkRepository jpaLinkRepository(
тоже исправлено в 7 пр)

2024-04-18 22:07 UTC, emapfff commented on scrapper/src/main/java/edu/java/domain/jpa/bases/BaseJpaChatRepository.java
> +    @Query("select c from Chat c where c.tgChatId= :tgChatId")
вообще можно, нужно попробовать

2024-04-20 23:47 UTC, emapfff commented
Привет! Все поправки были исправлены в 7 ПР, так как они схожи между собой и какие то моменты уже были исправлены в 7 ПР.

2024-04-21 23:04 UTC, iskanred commented
> Привет! Все поправки были исправлены в 7 ПР, так как они схожи между собой и какие то моменты уже были исправлены в ней.

Привет! Хорош посмотрю, тогда этот можешь мержить, наверн

2024-04-22 23:57 UTC, iskanred approved these changes
✅

2024-04-23 14:26 UTC, merged