Hw7
emapfff/java-backend-2024 pull request #11
Opened 2024-03-31 19:24 UTC by emapfff

2024-04-18 21:51 UTC, iskanred commented
> Привет! Седьмая готова к проверке. Учел недостаток с `@Primary`, который был в 6.

Привет! А остальные правки из 6го в каком PR вносить будешь?

2024-04-18 22:04 UTC, emapfff commented
> > Привет! Седьмая готова к проверке. Учел недостаток с `@Primary`, который был в 6.
> 
> Привет! А остальные правки из 6го в каком PR вносить будешь?
>
> сейчас, 5 минут

2024-04-18 22:08 UTC, iskanred requested changes
🔥 Все круто! Понравилась идея с наследованием от Reactor Retry, грамотно сделано! 

Советую еще глянуть bucket4j спринг бут стартер. Имлементить необязательно, но хотя бы, что он есть знать.

Не хватает только тестов на ретраи, но это добавтиь в твоей реализации недолго, просто сколько раз какой-то метод вызвался. Если придумаешь, как учитывать стратегию бэкоффа будет плюсом, но необязательно, потому что это уже слонжо. 

Поэтому пока 5/6. Отправляю на доработку в гитхабе и на портале)

Плюс, сейчас все параметры для ретраев у тебя стоят одни для всех клиентов. Хотя разные ресурсы (бот, гитхаб, стэк) могут отвечать с разной скоростью / разными статусами / быть не доступными. В общем лучше сделать так, чтобы можно было параметризировать политику ретраев для каждого клиента. В идеале, если еще и саму политику ретраев можно менять, например, одному ресурсу лучше linear retry, а другому - exponential или jitter. При было бы круто, если бы кол-во кода не возросло линейно. Можно иметь дефолтную родительскую реализацию политики ретраев и менять при необходимости или как-то по-другому сделать. Это необязательно, но было супер и приближенно к реальности!

В реальных проектах параметры ретраев относят к конфигу клиента:
```yaml
some-client:
    base-url: ...
    get-smth:
        url: ${base-url}/smth/
        ...
     retry-policy:
         backoff: 1s
         backoff-type: exponential
```

P.S. Прошу прощения за долгую проверку, был загружен

2024-04-18 22:08 UTC, iskanred commented on bot/pom.xml
> +            <version>8.1.0</version>
у bucket4j есть свой spring boot starter, который можно настроить через yaml конфиг и использовать встроенные аннотации. Так было бы попроще и поприятнее)

https://github.com/MarcGiffing/bucket4j-spring-boot-starter?tab=readme-ov-file#property-configuration-examples

2024-04-18 22:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +@EnableConfigurationProperties({ApplicationConfig.class, RateLimitingProperties.class})
я бы указал пакет сразу, потом мб еще появятся проперти классы

2024-04-18 22:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/backoff/ConstantBackOff.java
> +
у тебя как-будто вся эта часть почти одинакова для всех ретраев

можно всю похожую логику вынести в абстрактный класс вынести, в конкретных реализациях уже просто переопределять `duration()`

2024-04-18 22:08 UTC, iskanred commented on bot/src/main/java/edu/java/bot/configuration/RetryConfig.java
> +    @ConditionalOnProperty(prefix = "retry", name = "back-off-type", havingValue = "linear")
бинами можно сделать прям над классами `@Component`-ом, conditional там же поставить можно

2024-04-21 23:18 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +@EnableConfigurationProperties({ApplicationConfig.class, RateLimitingProperties.class})
`@ConfigurationPropertiesScan`

2024-04-23 14:25 UTC, emapfff commented
> 🔥 Все круто! Понравилась идея с наследованием от Reactor Retry, грамотно сделано!
> 
> Советую еще глянуть bucket4j спринг бут стартер. Имлементить необязательно, но хотя бы, что он есть знать.
> 
> Не хватает только тестов на ретраи, но это добавтиь в твоей реализации недолго, просто сколько раз какой-то метод вызвался. Если придумаешь, как учитывать стратегию бэкоффа будет плюсом, но необязательно, потому что это уже слонжо.
> 
> Поэтому пока 5/6. Отправляю на доработку в гитхабе и на портале)
> 
> Плюс, сейчас все параметры для ретраев у тебя стоят одни для всех клиентов. Хотя разные ресурсы (бот, гитхаб, стэк) могут отвечать с разной скоростью / разными статусами / быть не доступными. В общем лучше сделать так, чтобы можно было параметризировать политику ретраев для каждого клиента. В идеале, если еще и саму политику ретраев можно менять, например, одному ресурсу лучше linear retry, а другому - exponential или jitter. При было бы круто, если бы кол-во кода не возросло линейно. Можно иметь дефолтную родительскую реализацию политики ретраев и менять при необходимости или как-то по-другому сделать. Это необязательно, но было супер и приближенно к реальности!
> 
> В реальных проектах параметры ретраев относят к конфигу клиента:
> 
> ```yaml
> some-client:
>     base-url: ...
>     get-smth:
>         url: ${base-url}/smth/
>         ...
>      retry-policy:
>          backoff: 1s
>          backoff-type: exponential
> ```
> 
> P.S. Прошу прощения за долгую проверку, был загружен

Вроде выполнил переписал архитектуру ретраев, было непросто) Тесты для клиентов учитывают ретраи, там стоят заглушки которые n раз возвращают 500 ошибку, а на n + 1 возвращает 200, при чем у каждого retry max-attempts = n + 1. Вроде все замечания учел.

2024-04-23 16:18 UTC, iskanred requested changes
Все очень здоров выглядит, капитальный красавчик!

Единственное, что мы получается протестили успешный кейс ретраев, когда они все-таки срабатывают. Но не хватает и неуспешного:

Проверить, что обращений к серверу было n раз + и в итоге клиент выкинул ошибку соответствующую

Здесь пока еще закинул на изменения, но на портале оценку поменял на 6/6 💯

2024-04-23 16:18 UTC, iskanred commented on scrapper/src/test/java/edu/java/backoff/ExponentialBackOffTest.java
>              .expectNoEvent(Duration.ofSeconds(8))
оо, круто сделал прям! среди моих студентов так сделать никто не догадался, мощно!!!

2024-04-30 19:57 UTC, iskanred approved these changes
✅

2024-04-30 20:02 UTC, merged