Hw8
emapfff/java-backend-2024 pull request #12
Opened 2024-04-07 20:22 UTC by emapfff

2024-04-25 19:34 UTC, iskanred requested changes
🔥 Здорово, выяглидт красиво!

Жаль, не успел реализовать DLQ, хотел бы увидеть)

+ Вообще никаких тестов на кафку не увидел, к сожалению(
Тестов на историю с отправкой в dlq, на консьюмеры и продюсеры
Если сложно и нужно поднимать кафковый тест-контейнер, то мб и пофин, но увидеть хочется хотя бы базу, которую можно замокать. + Тесты на поведение с DLQ увидеть все-таки хотелось бы)

Из-за этого всего пока 4/6 (-1 за отсутствие любых тестов, -1 за отсутствие обработки невалидных сообщений и отправкой в DLQ)

Как обычно, отправил на доработку на портале и на гитхабе)
Жду!)

2024-04-25 19:34 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/BotQueueConsumer.java
> +        log.info("{} {} {}", linkUpdateRequest.description(), linkUpdateRequest.url(), linkUpdateRequest.id());
не сделал отправку в DLQ?

2024-04-25 19:34 UTC, iskanred commented on compose.yml
> +  kafka-2:
за два брокера респект!

2024-04-25 19:34 UTC, iskanred commented on compose.yml
> +      - zookeeper
зукипер моежт стартовать, но еще не быть готовым к действиям, поэтому рекомендую изучать readiness пробы в docker-compose, а именно condition'ы и healthcheck'и

https://docs.docker.com/compose/startup-order/
https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

Вероятно, тут оно конкретно не нужно, но просто для информации)

2024-04-25 19:34 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/KafkaConfig.java
> +    public NewTopic topic(TopicProperties topicProperties) {
а для чего это, не подскажешь?

2024-04-26 00:45 UTC, emapfff commented on bot/src/main/java/edu/java/bot/service/BotQueueConsumer.java
> +        log.info("{} {} {}", linkUpdateRequest.description(), linkUpdateRequest.url(), linkUpdateRequest.id());
будет сделано!

2024-04-26 00:45 UTC, emapfff commented on compose.yml
> +      - zookeeper
хорошо!

2024-04-26 00:46 UTC, emapfff commented on scrapper/src/main/java/edu/java/configuration/KafkaConfig.java
> +    public NewTopic topic(TopicProperties topicProperties) {
разве не для того, что админ кафки создавал внутри топик, нужно изучить

2024-04-26 23:20 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/KafkaConfig.java
> +    public NewTopic topic(TopicProperties topicProperties) {
по идее можно без этого, если кафку в компоузе развернуть, но я не уверен, может, чего-то не знаю

2024-04-30 20:29 UTC, iskanred approved these changes
✅

6/6 💯

на портале изменил оценку

2024-04-30 20:38 UTC, merged