Hw2
emapfff/java-backend-2024 pull request #3
Opened 2024-02-25 12:24 UTC by emapfff

2024-02-28 18:00 UTC, iskanred requested changes
💯 За вторую домашку ставлю 6/6, все гуд !

Но в целом по архитектуре и не только требуются правки. Желательно успеть их внести до дедлайна третьей домашки. Можешь отпочковать ветку HW3 от HW2 и сделать PR в main. Потому что правки по конкретной домашке лучше вносить в этом же PR, а не в другом. Можешь использовать механизм запроса ревью в гитхабе, когда внесешь правки или написать сразу мне в телеге. 

По вопросам тоже можешь мне в личку заходить)

Хочется еще отметить, что круто придумываешь рекорды и configurationproperties, впечатлил)

2024-02-28 18:00 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> +    private static ApplicationConfig applicationConfig;
лучше не использовать статические поля + если нужно выполнить какой-то метод при старте приложения (например, запуска бота) это лучше делать средставми спринга

Можешь запускать бота, например в `@PostConstruct ` или каким-либо другим способом:
https://habr.com/ru/articles/572828/

Также советую вынести бота в отдельный бин и подтягивать его сюда автоматически

2024-02-28 18:00 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/Bot.java
> +        BotCommand listCommand = new BotCommand("/list", "показать список отслеживаемых ссылок");
можешт сделать классы команд бинами и просто объявить в конструкторе параметр `List<Command> commands`, спринг сам положит туда все бины этого типа

Но тогда нужно самого бота сделать бином, поставив над классом `@Component`

Тогда вряд ли получится сохранить паттерн цепочки обязанностей, как ты реализовал, но зато при добавлении команды достаточно будет только добавить класс этой команды, сделав бином

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +    }
Можешь использовать Lombok и поставить над классом аннотацию `@AllArgsConstructor`, ломбок сам в compile-time сгенерит конструктор, а спринг в рантайме уже подятнет в него бины

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/ScrapperApplication.java
> +    }
question: а это для чего?)

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/LinkUpdaterScheduler.java
> +        LOGGER.info("Update");
логгер можно через Lombok cоздавать, используя `@Log4j` аннотацию

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +        return this.webClient.get().uri("/users/{user}", user).retrieve().bodyToMono(GitHubUserResponse.class).block();
Вообще рекомедную, конечно, не использовать `block()` и возвращать Mono, чтобы пощупать реактивное программирование немного. Для такого простого проекта в целом норм, но вообще было бы круто познакомиться хотя бы ненмого с WebFlux и работй с WebClient

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/GitHubClientInterface.java
> +public interface GitHubClientInterface {
вообще не особо хорошая практи использовать `Interface` или `I` или `Impl`. Интерфейс должен иметь общее название, которое соответствовало тому, что он позволяет сделать. А реализация должна указывать на свою особоенность.

Например `GitHubWebClient` или `AsyncGitHubClient`

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @NotNull @Bean Scheduler scheduler
style: анноташки лучше ставить друг на друга 😅

+ `@NestedConfigurationProperties`

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +    }
для собственно написанных классов лучше ставить аннотации `@Component` над классом, а не делать конфигурации. Конфигурации объявляют для библиотечных классов.

не помню, писал ли об этом в своем ревью тебе уже, но вообще пишу это ребятам уже раз 10й))
обрати внимание, пожалуйста! 🙏

2024-02-28 18:00 UTC, iskanred commented on scrapper/src/main/java/edu/java/responses/RepositoryResponse.java
> +    @JsonProperty("name") String repoName,
тут чето пробельчик съехал

2024-03-01 16:26 UTC, iskanred requested changes
Уже хорошо! Не стесняйся в личку писать, разберемся, как команды сбиндить

2024-03-01 16:26 UTC, iskanred commented on scrapper/src/test/java/edu/java/clients/GitHubClientTest.java
> +        assert repositoryResponse != null;
блин, ассерты лучше в тестах не использовать, в junit должна быть assetNotNull функция

2024-03-01 16:26 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
пока не пробовал использовать `@NestedConfigurationProperties`? вместо `@Bean`?

2024-03-01 16:26 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/StackOverflowClient.java
> +        return this.stackOverflowClient.get().uri("/questions/{id}?site=stackoverflow", id)
цепочку методов, которые как-то конфигурируют класс или билдят лучше выносить один за одним

```java
...
.get(...)
.uri(...)
.retrieve(...)
.bodyToMono(...)
```

2024-03-01 17:30 UTC, emapfff commented on scrapper/src/main/java/edu/java/configuration/ApplicationConfig.java
> +    @Bean
забыл...(

2024-03-03 17:28 UTC, merged