Hw3
emapfff/java-backend-2024 pull request #4
Opened 2024-03-03 17:24 UTC by emapfff

2024-03-11 20:46 UTC, iskanred commented
Хотелось бы увидеть скрины Swagger UI)

2024-03-12 00:11 UTC, iskanred requested changes
Не хватает тестов для контроллеров(
Хочется увидеть особенно тестирование исключительных кейсов, когда возвращаться должен не 2xx статус код.

В целом все круто сделал 🔥, но не хватает тестов + много правок нужно внести.

Пока ставлю 5/6 и отправляю на доработку, как исправить и добавишь тесты, запрашивай ревью, поставлю 6ку)

+был бы рад увидеть скрины Swagger UI в PR

P.S. Прошу прощения за долгую проверку дз№3, был сильно занят прошлую неделю

2024-03-12 00:11 UTC, iskanred commented on models/src/main/java/dto/AddLinkRequest.java
> +    @JsonProperty("link") String link
если что, можешь не использовать `@JsonProperty` постоянно, а полагаться на название поля, которое Jackson сам сериализует в json-поле с таким же названием

2024-03-12 00:11 UTC, iskanred commented on models/src/main/java/dto/LinkResponse.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
question: почему где-то стоит аннотация, а где-то нет?

Нужна ла она вообще в `*Response` классах?

2024-03-12 00:11 UTC, iskanred commented on models/src/main/java/dto/LinkUpdateRequest.java
> +    @JsonProperty("url") String url,
не задумывался над тем, чтоб хранить сразу URI объект вместо строки? Jackson десериалузет сам и в случае чего ошибку выплюнет, которая в 400, допусутим, можно скастить, если URI невалидный.
Можно в инете почитать, мб что-то такое:

https://stackoverflow.com/questions/60562734/replace-url-fields-by-uri-with-jackson

2024-03-12 00:11 UTC, iskanred commented on models/src/main/java/exceptions/AbsentChatException.java
> +}
`Exception`-классы не стоит выносить в отдельный модуль. Пусть модули сами решают, какой Exception им использовать, например, где-то будет наследоваться от `RuntimeException`, чтобы не чекать каждый или кастомный предок будет.

DTO-классы с другой стороны всегда должны быть и будут одинаковые, так как оба модуля (bot и scrapper) придерживаются одних и тех же контрактов по взаимодействию

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +    private final String chatId = "Tg-Chat-Id";
Мб стоит задуматься над тем, чтобы выносить такие проперти в `application.yaml`? Все свойства выносить в `@ConfigurationProperties` отдельным классом (`scrapper-client` - `ScrapperClientProperties`), либо черз ApplicationConfig подтянуть. Может меняться URL или название заголовка, и менять это дело в коде тяжелее, чем в вынесенный наружу конфиг файл 

А к текущей реализации: сделать эти поля надо static и желательно назвать большими буквами)

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/BotController.java
> +    public Mono<Void> sendUpdates(@RequestBody LinkUpdateRequest linkUpdateRequest)
почему `Mono`?)

тут лучше пока оставить просто void

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/controller/BotController.java
> +        if (linkUpdateRequest == null) {
возможно, эта проверку стоит потом вынести глубже в сервисный слой либо завести валидатор на этом слое

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/handler/ApiErrorHandler.java
> +        return new ResponseEntity<>(apiResponse, HttpStatus.BAD_REQUEST);
`<>` здесь вряд ли нужны

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/handler/ApiErrorHandler.java
> +        return new ResponseEntity<>(apiResponse, HttpStatus.BAD_REQUEST);
можно поставить аннотацию `@ResponseStatus(...)` над методом и возвращать здесь просто `apiResponse`

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/handler/ApiErrorHandler.java
> +            "400",
статус-код можно вытащить так: `HttpStatus.BAD_REQUEST.toString()` ну или как-то так, точно не помню)

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/handler/ApiErrorHandler.java
> +            "IncorrectParameters",
имя можно вытащить, если сделать кастомные `Exception`-классы и там сделать параметр `name` либо так:
```java
exception.getClass().getSimpleName()
```

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/Bot.java
> +@Component(value = "bot")
да имя бина вроде берется из названия класса с маленькой буквы и так)

2024-03-12 00:11 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> -    }
question: а это куда теперь мигрировало?

2024-03-12 00:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/ScrapperController.java
> +    public Mono<Void> registrationChat(@PathVariable(value = "id") Integer id) throws IncorrectParametersExceptions {
опять `Mono`)

2024-03-12 00:11 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/ScrapperController.java
> +            throw new IncorrectParametersExceptions("");
пустое сообщение передавать - не очень хороший вариант, лучше написать, в чем дело

2024-03-12 00:11 UTC, iskanred commented on scrapper/src/test/java/edu/java/clients/BotClientTest.java
> +                "\"tgChatIds\": [1, 2, 3]}")));
ну такое лучше, конечно, в отдельную переменную положить

2024-03-13 06:51 UTC, emapfff commented on models/src/main/java/dto/LinkResponse.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
не нужно, просто копи пастил из прошлых респонс классах)

2024-03-13 06:57 UTC, emapfff commented on models/src/main/java/dto/LinkUpdateRequest.java
> +    @JsonProperty("url") String url,
да я так и хотел, просто в документации для поля url нужно было хранить именно как строку, поэтому так и реализовал

2024-03-13 10:09 UTC, emapfff commented on bot/src/main/java/edu/java/bot/BotApplication.java
> -    }
хотел спросить по поводу данного пункта: после запуска спринга в логах нет информации об успешном создании бина botApplication, а после остановки в логах светится warn с такой подписью:
WARN  [restartedMain                 ] {} bServerApplicationContext -- Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'botApplication': Invocation of init method failed
![Uploading 2024-03-13_13-09-37.png…]()

2024-03-13 10:14 UTC, emapfff commented on bot/src/main/java/edu/java/bot/clients/ScrapperClient.java
> +    private final String chatId = "Tg-Chat-Id";
Да, хорошее решение, так же как вынесение базовых урлов для клиентов.

2024-03-13 16:42 UTC, iskanred commented on bot/src/main/java/edu/java/bot/BotApplication.java
> -    }
давай в тг обсудим

2024-03-14 07:12 UTC, emapfff commented
![2024-03-14_10-10-46](https://github.com/emapfff/java-backend-2024/assets/88779154/82d41103-3f27-41a0-b9b9-167113b56af6)
![2024-03-14_10-10-46](https://github.com/emapfff/java-backend-2024/assets/88779154/e9723909-abb9-4935-bf9e-830f88b5a0e9)
![2024-03-14_10-11-02](https://github.com/emapfff/java-backend-2024/assets/88779154/677c26ba-a94b-4324-8030-414732e856e0)
![2024-03-14_10-11-20](https://github.com/emapfff/java-backend-2024/assets/88779154/f5a04977-e1ab-453d-851d-9e3e0b7585e5)
![2024-03-14_10-11-43](https://github.com/emapfff/java-backend-2024/assets/88779154/3bd36114-de3a-4b06-8fa5-a6d4b9a92f78)
![2024-03-14_10-12-01](https://github.com/emapfff/java-backend-2024/assets/88779154/06ce0b73-f871-42e1-b973-556dfc12ca2b)
![2024-03-14_10-12-11](https://github.com/emapfff/java-backend-2024/assets/88779154/2bd2f7e6-2bd1-49d2-9e2d-b1eb945ba606)

2024-03-14 17:47 UTC, iskanred approved these changes
✅ 8/8 Ставлю аппрув, но рекомендую правки внести, можно у меня ревью по этому PR не запрашивать тогда, а исправить и влить, т.к. правки минорные и их мало. Если будут вопросы, welcome to телеграм)

2024-03-14 17:47 UTC, iskanred commented on models/src/main/java/dto/ApiErrorResponse.java
>      @JsonProperty("code") String code,
во всех модельках можно убрать ненужные `@JsonProperty` аннотации

2024-03-14 17:47 UTC, iskanred commented on models/src/main/java/dto/RemoveLinkRequest.java
> +    String link
не пытался пробовать в реквест DTO сунуть `URI link` а не `String link`? У кого-то все норм так, получилось

2024-03-14 17:47 UTC, iskanred commented on bot/src/main/java/edu/java/bot/handler/ApiErrorHandler.java
> +            exception.getClass().getSimpleName(),
я бы все-таки порекомендовал добавить поле `name` в кастомный эксепшн, а так вывод сейчас будет `IncorrectParametersExceptions` вместо `Incorrect Parameters`

`+` почему IncorrectParametersException_**s**_ во множественном числе?)

2024-03-14 17:49 UTC, iskanred commented
+Жду тогда PR по боту. Присылай тоже в личку, как закончишь

P.S. оценку на платформе исправил)

2024-03-14 21:20 UTC, merged