Hw4
emapfff/java-backend-2024 pull request #6
Opened 2024-03-09 08:07 UTC by emapfff

2024-03-14 17:51 UTC, iskanred commented on coverage-error.log
> +[2024.02.15 07:04:43] (Coverage ERROR): Failed to parse agent arguments
это ты так хочешь спросить, в чем проблема?))

2024-03-14 18:09 UTC, iskanred requested changes
🔥 8/8 все круто, но есть небольшие пометки

Присылай на ревью, как внесешь правки)

2024-03-14 18:09 UTC, iskanred commented on coverage-error.log
> +[2024.02.15 07:04:43] (Coverage ERROR): Failed to parse agent arguments
это ты так хочешь спросить, в чем проблема?))

если да, то лучше заходи в тг

2024-03-14 18:09 UTC, iskanred commented on migrations/change-log.xml
> +    </changeSet>
question: почему решил побить на три отдельных changeSet, а не в одном все сделать?

2024-03-14 18:09 UTC, iskanred commented on migrations/master.xml
> +    <include file="change-log.xml"/>
question: а почему бы все сюда не перенести? зачем отдельный файл для этого? обычно в мастере уже хранят все нужные changeSet, с вложенностью тяжеловато работать

2024-03-14 18:09 UTC, iskanred commented on migrations/sql/createTableChatDB.sql
> +    name TEXT      NOT NULL,
а зачем чату имя? на всякий случай?)

2024-03-14 18:09 UTC, iskanred commented on migrations/sql/createTableLinkDB.sql
> +    url         VARCHAR(500) NOT NULL,
стало интересна максимальная длина урлов, включая весь path

макс. длина доменного имени - 63
а, включая path - около 2000 в зависимости от браузера и сервера

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

Так что лучше поставить `TEXT` и не париться)

2024-03-14 21:39 UTC, emapfff commented on migrations/sql/createTableChatDB.sql
> +    name TEXT      NOT NULL,
думал хранить имя юзера, типа такого )

2024-03-15 01:04 UTC, emapfff commented on migrations/master.xml
> +    <include file="change-log.xml"/>
в инете читал, что лучше change-log разбивать на множество файлов: "Хорошей практикой считается создавать множество changeLog и "включать" их в другие changeLog. Таким образом у вас будет множество файлов, а не один большой манускрипт, ведь changeSet-ов будет очень много со временем"
https://struchkov.dev/blog/ru/get-started-liquibase/

2024-03-17 15:16 UTC, iskanred commented on migrations/master.xml
> +    <include file="change-log.xml"/>
хорошо, рад, что изучаешь!

2024-03-17 15:17 UTC, iskanred approved these changes
✅

2024-03-17 17:29 UTC, merged