Hw5
emapfff/java-backend-2024 pull request #8
Opened 2024-03-17 18:06 UTC by emapfff

2024-03-26 19:20 UTC, iskanred commented
> Привет! Вроде все реализовал, добавил парсера для юрлок. Внутри бота пока не реализована вся логика, буду дополнять, пока на данный момент кое как все взаимодействует) Сконнектил бота и скраппера. Полностью его переписал (извиняюсь что все одном пр, совсем забыл разделить), забинил команды и все ваще супер смотрится). Есть несколько моментов по поводу запросов, а именно обработка их исключений: сейчас вся бизнес логика контроллеров лежит на слое jdbc сервисов (там происходит обработка ошибок hedears, params и body) и при тестинге апишки все ошибки корректно обрабатываются. Однако я не до конца не понимаю как эти ошибки можно выплюнуть в бота (т.е. когда бот получает сообщение о добавлении ссылки в бд, а далее через скраппер клиента я посылаю запрос add, где внутри я обрабатываю валидность ссылки). Я понимаю что можно обрабатывать ссылки на уровне бота, однако тогда бот и скраппер не будут взаимосвязанными. Пока на это не нашел решения, но сейчас добавление и удаление ссылок, авторизация юзера проходят успешно). Тесты для бота, буду писать как все подключу.
> 
> p.s.некоторые моменты были исправлены в бонсуном пр.

Проверять валидность ссылки на старте можно и нужно прям в боте - проверить, что мы поддерживаем такой ресурс, что ссылка валидная (регуляркой можно чекнуть) и что ресурс отвечает (пигнануть ресурс). Тогда можно сразу пользователю ответить, что он попытался добавить кривую ссылку.

А если, допустим, ресурс был недоступен в момент, когда мы его опрашивали (т.е. потенциально он может быть недоступен теперь навсегда), то можно просто дергнуть отдельную ручку на контроллере сервиса бота, который дальше уже отправить сообщение пользаку

В общем, я за валидацию на уровне бота, а за обработку исключительных ситуаций на уровне скраппера

2024-03-26 20:07 UTC, iskanred requested changes
Сейчас все выглядит гораздо лучше и приятнее 🔥
Здорово постарался! 💪

Единственное, хочется увидеть тесты на сами сервисы, которые добавил в рамках домашки, поэтому пока 7/8 и отправка на доработку в гитхабе и на портале

+всякие замечания, но это в рамках нормы, потому что ревью оно для того и надо)

Что касается валидации ссылок, то лучше все, что можно вынести в бота - вынести в бота.
Это как с валидацией на сайтах: все, что можно провалидировать на фронтенде, лучше валидировать там (типа почты или длины пароли). Тогда пользователь быстрее получит фидбек и мы не будем лишний раз нагружать сеть заведомо неверными запросами.

Как добавишь тесты и внесешь правки, присылай ревью на гитхабе и на портале тоже отправляй в статус для проверки + лучше сразу в телеге напиши, чтобы я быстрее проверил)

2024-03-26 20:07 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/Command.java
> +    String command();
`command.command()` получается?)

мб лучше `name()` назвать?

2024-03-26 20:07 UTC, iskanred commented on bot/src/main/java/edu/java/bot/commands/Command.java
> +        return new BotCommand(command(), description());
🔥

2024-03-26 20:07 UTC, iskanred commented on bot/src/main/java/edu/java/bot/service/Bot.java
> +                if (message.equals(command.command())) {
можно, кстати, перегнать список команд в мапу в конструкторе и хранить его как мапу
```java
Map<String, Command>
```
Тогда можно не пробегаться каждый раз по списку командуи логика чуть упростится

2024-03-26 20:07 UTC, iskanred commented on bot/src/test/java/edu/java/bot/commands/BotTest.java
> +public class BotTest {
тесты в каком PR ждать?)

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/LinkUpdaterScheduler.java
> +        //linkUpdaterService.checkUpdates();
ты тестил? а тут чето закомментированно и непонятно, проверял ли ты работу, потому что сейчас требование из дз не выполняется

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/controller/ScrapperController.java
> +    public Mono<ListLinksResponse> getLinks(@RequestHeader("Tg-Chat-Id") Long tgChatId) {
`Mono` не используют в контроллере, т.к. он тут просто не нужен

`Mono` - объект-обещание для асинхронных операций - чаще всего вызовов по сети => для клиентов, а не контроллеров

надо везде в контроллерах убрать `Mono` и оставить просто `ListLinksResponse`, а спринг сам завернет это в `ResponseEntity<ListLinksResponse>` со статусом 200

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/dto/ChatDto.java
> +@Setter
`@Data` включает в себя `@Getter` и `@Setter`:
https://projectlombok.org/features/Data

почему решил не использовать `record` вместо дата-класса?

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/dto/ChatDto.java
> +}
здесь не надо сделать дата-классом или рекордом? лучше сделать

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/domain/repository/JdbcChatRepository.java
> +    @Transactional
транзакции обычно на сервисном слое происходят и там где, действительно требуется.

проанализируй, в каких местах действительно нужен транзакционный вызов, а где не нужно - надо убрать

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +        }
можно использовать switch-case, будет нагляднее, по крайней мере с java 17

хотя по идее это если енамы, можно и на более ранних версиях

так будет и красивее и надежнее, т.к. при добавлении нового ресурса, выскочит ошибка компиляции и не забудешь везде в такие проверки добавить новый ресурс и вызов нового клиента

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +        } catch (Exception exception) {
а если база вдруг стала недоступна, это еще не факт, что ссылка не найдена

надо сузить тип exception'а, глянуть, как это можно сделать

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/updaters/GithubUpdater.java
> +    }
если апдейтов только 0 или 1, то мб лучше сделать `boolean hasUpdates()` ?

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/scheduler/LinkUpdaterService.java
> +            if (linkParse.parse(link.getUrl()).equals(Urls.GITHUB)) {
тут тоже лучше свитч кейс юзать

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/test/java/edu/java/domain/repository/JdbcChatRepositoryTest.java
> +    @Rollback
если аннотация у всех методов, можно перенести на уровень класса, как правило

+вроде же ее значение и так `true` по дефолту для spring test context:

> Rollback for integration tests in the Spring TestContext Framework defaults to `true` even if `@Rollback` is not explicitly declared.

https://docs.spring.io/spring-framework/reference/testing/annotations/integration-spring/annotation-rollback.html

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/test/java/edu/java/tools/LinkParseTest.java
> +@SpringBootTest
ты тут для теста поднимаешь весь контекст спринга => все бины, хотя используешь только один

Можно указать в этой анноташке списком все бины, которые нужны для теста

2024-03-26 20:07 UTC, iskanred commented on scrapper/src/test/java/edu/java/updaters/GithubUpdaterTest.java
> +@SpringBootTest
тут тоже

2024-03-27 17:08 UTC, emapfff commented on scrapper/src/main/java/edu/java/LinkUpdaterScheduler.java
> +        //linkUpdaterService.checkUpdates();
да, все работает, только у меня падает сервис из за того количество запросов на апи ограничено

2024-03-27 18:39 UTC, emapfff commented on bot/src/main/java/edu/java/bot/service/Bot.java
> +                if (message.equals(command.command())) {
точняк!

2024-03-27 18:39 UTC, emapfff commented on bot/src/test/java/edu/java/bot/commands/BotTest.java
> +public class BotTest {
в этом же)

2024-03-27 21:42 UTC, emapfff commented on scrapper/src/test/java/edu/java/tools/LinkParseTest.java
> +@SpringBootTest
Лучше же будет @JdbcTest, нет ?

2024-04-04 19:26 UTC, iskanred approved these changes
Тогда этот PR аппрувлю ✅
Буду смотреть следующий)

Оценку за дз5 принял на 8/8 💯

2024-04-07 19:16 UTC, merged