Hw5 bonus
emapfff/java-backend-2024 pull request #9
Opened 2024-03-17 18:25 UTC by emapfff

2024-03-26 20:32 UTC, iskanred requested changes
14/15 - не хватает тестов на jooq репозитории

тесты на сервисы надо добавить в рамках основного ДЗ_5, ровно как и внести другие правки)

Сделано все грамотно, но опять же активно советую, чтобы сервисы сделать независимыми от реализации репозиторев!

Отправляю дз на дорабтку в гитхабе и на портале.

Как добавишь тесты и внесешь правки, присылай ревью на гитхабе и на портале тоже отправляй в статус для проверки + лучше сразу в телеге напиши, чтобы я быстрее проверил) - поставлю фулл

2024-03-26 20:32 UTC, iskanred commented on scrapper-jooq/pom.xml
> +        </dependency>
этот модуль - "библиотечный" и не подразумевает использование спринга. Ну ты его и не используешь)

Так что можешь зависимости на спринг удалить, они не нужны

2024-03-26 20:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/LinkUpdaterScheduler.java
> +        //linkUpdaterService.checkUpdates();
до сих пор закомментированно :/

2024-03-26 20:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/clients/GitHubClient.java
> +    public Flux<BranchResponse> fetchBranch(String user, String repo) {
почему `Flux`, а не `Mono`?

2024-03-26 20:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/responses/BranchResponse.java
> +    @JsonProperty("name") String name,
можно не ставить, jackson возьмет имя поля)

2024-03-26 20:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/responses/BranchResponse.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
кажется, опять ненужная анноташка всплыла

2024-03-26 20:32 UTC, iskanred commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +public class JdbcLinkService implements LinkService {
несмотря на ТЗ домашки, рекомендую каждый сервис сделать в количестве одного экземпляра, не разбивая на разные реализации репозиториев, чтобы соблюдать принцип инверсии зависимостей из `SOLID`. Высокоуровневая абстракция типа сервиса не должна зависить от деталий реализации низкоуровневой типа репозитория.

Т.е. лучше сделать единые интерфейсы `LinkRepository` и `ChatRepository`, а их уже реализовывать классами типа `JdbcLinkRepository`, `JooqLinkRepository`, `JpaLinkRepository` и т.д.

А в сервисах уже можно полагаться только на интерфейсы репозиториев. А выбирать конкретную реализацию можно через `@Qualifier`, `@Primary` или `@Conditional...` аннотации (как в 6й домашке)

2024-03-29 01:22 UTC, emapfff commented on scrapper/src/main/java/edu/java/service/jdbc/JdbcLinkService.java
> +public class JdbcLinkService implements LinkService {
Тогда зачем в тз 6 домашки мы добавляем новое свойство в appliсation.yml, если мы можем подтягивать определенные бины для репозиториев ручками и указывать их реализацию через анноташки как @Qualifier. Если придерживаться условиям из шестой ТЗ, то нужно через @Qualifier для всех даошек в сервисе указывать одну и ту же их реализацию( к примеру только jdbc либо jooq или же jpa), т.к. по @ConditionalOnProperty у нас подтянуться только бины определенного репозитория. Я почитал в инете и действительно по SOLID  принципам нужно отделять сервисы от реализации репозиториев, и стоит через какой нибудь доп слой выбирать нужный тип репозитория. Теперь вопрос: мы можем в одном сервисе применять различные типы репозиториев и зачем?

2024-04-04 22:20 UTC, iskanred requested changes
Остались минорные правки.

🔥 Решение выглядит лаконично!
💯 Принимаю на портале с 15/15. Здесь еще отправляю запрос на изменения.

Можно еще подумать в сторону того, чтобы в `Urls` (лучше переименовать в `Resource`) енаме указывать паттерн регулярку полем енама (передав в конструктор). Тогда можно было бы пройти по `Resource.values()` и в зависимости от того, под какой паттерн смэтчилась строка, возвращать этот инстанс. Т.е. не делать еще один `if-else` в `LinkParse` (лучше переименовать в `LinkParser`).

2024-04-04 22:20 UTC, iskanred commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +    @Primary
question: а зачем тут primary? у нас же есть `@ConditionalOnProperty`

2024-04-04 22:20 UTC, iskanred commented on scrapper/src/test/java/edu/java/domain/jooq/JooqChatRepositoryTest.java
> +@SpringBootTest(properties = "app.database-access-type=jooq")
ты тут, по-моему, опять весь контекст поднимаешь, хотя по факту нужен только бин репозитория или конфгурации, ну и dslcontext и мб еще что-то

2024-04-04 22:42 UTC, emapfff commented on scrapper/src/test/java/edu/java/domain/jooq/JooqChatRepositoryTest.java
> +@SpringBootTest(properties = "app.database-access-type=jooq")
До указания properties я локально поднимал только то, что нужно, но блин там столько нужно указать и написать для каждого отельные конфиг файлы-разве это норм ?

2024-04-04 22:48 UTC, emapfff commented on scrapper/src/main/java/edu/java/configuration/JdbcConfig.java
> +    @Primary
согласен!

2024-04-07 15:53 UTC, iskanred approved these changes
✅

2024-04-07 15:53 UTC, iskanred commented on scrapper/src/test/java/edu/java/domain/jooq/JooqChatRepositoryTest.java
> +@SpringBootTest(properties = "app.database-access-type=jooq")
в целом, как удобнее)

2024-04-07 19:16 UTC, merged